development:
  clients:
    default:
      database: qsmk_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: qsmk_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

testing:
  clients:
    default:
      database: <%= ENV['MONGOID_DATABASE'] %>
      hosts:
        - <%= ENV['MONGOID_HOST'] %>
      options:
        user: <%= ENV['MONGOID_USERNAME'] %>
        password: <%= ENV['MONGOID_PASSWORD'] %>        
  options:
    raise_not_found_error: false
staging:
  clients:
    default:
      database: <%= ENV['MONGOID_DATABASE'] %>
      hosts:
        - <%= ENV['MONGOID_HOST'] %>
      options:
        user: <%= ENV['MONGOID_USERNAME'] %>
        password: <%= ENV['MONGOID_PASSWORD'] %>        
  options:
    raise_not_found_error: false
production:
  clients:
    default:
      database: <%= ENV['MONGOID_DATABASE'] %>
      hosts:
        - <%= ENV['MONGOID_HOST'] %>
      options:
        user: <%= ENV['MONGOID_USERNAME'] %>
        password: <%= ENV['MONGOID_PASSWORD'] %>
        auth_source: <%= ENV['MONGOID_AUTH_SOURCE'] %>
  options:
    raise_not_found_error: false
